default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  api_dir: '_api/'

stages:
  - Test
  - Build
  - Deploy

test_job:
  stage: Test
  script:
    - 'cd $api_dir'
    - 'dotnet test --no-restore'
  only:
    - merge_requests

build_job:
  stage: Build
  script:
    - 'cd $api_dir'
    - 'dotnet restore'
    - 'dotnet build --no-restore'
  only:
    - merge_requests
