default:
  image: mcr.microsoft.com/dotnet/sdk:6.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    
variables:
  api_dir: '_api/'

stages:
  - Test
  - Build
  - Deploy

test_job:
  stage: Test
  script:
    - 'cd $api_dir'
    - 'dotnet test --no-restore'

build_job:
  stage: Build
  script:
    - 'cd $api_dir'
    - 'dotnet restore'
    - 'dotnet build --no-restore'
