workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH

default:
  image: node

variables:
  spa_dir: '_spa/react-spa/'

cache:
  paths:
    - _spa/react-spa/node_modules/

stages:
  - Test
  - Build
  - Deploy

test_job:
  stage: Test
  script:
    - 'cd $spa_dir'
    - 'npm install'
    - 'npm test'

build_job:
  stage: Build
  script:
    - 'cd $spa_dir'
    - 'npm install'
    - 'npm test'
